package com.bpps.pojo;
// Generated 2012-6-10 23:02:51 by Hibernate Tools 3.2.1.GA

import org.apache.struts.upload.FormFile;




/**
 * Disease generated by hbm2java
 */
public class Disease extends org.apache.struts.action.ActionForm  implements java.io.Serializable {


     private Integer disId;
     private String disName;
     private String disNameEn;
     private String disIntroduction;
     private String disContent;
     private FormFile disImage;
     private String disImagePath;
     private Integer labelId;
     private String disPreventionContent;
     private String disSpectrum;

    public Disease() {
    }

    public Disease(String disName, String disNameEn, String disIntroduction, String disContent) {
       this.disName = disName;
       this.disNameEn = disNameEn;
       this.disIntroduction = disIntroduction;
       this.disContent = disContent;
    }
   
    public Integer getDisId() {
        return this.disId;
    }
    
    public void setDisId(Integer disId) {
        this.disId = disId;
    }
    public String getDisName() {
        return this.disName;
    }
    
    public void setDisName(String disName) {
        if(disName==null)
            disName = "";
        this.disName = disName;
    }
    public String getDisNameEn() {
        return this.disNameEn;
    }
    
    public void setDisNameEn(String disNameEn) {
        if(disNameEn==null)
            disNameEn = "";
        this.disNameEn = disNameEn;
    }
    public String getDisIntroduction() {
        return this.disIntroduction;
    }
    
    public void setDisIntroduction(String disIntroduction) {
        if(disIntroduction==null)
            disIntroduction = "";
        this.disIntroduction = disIntroduction;
    }
    public String getDisContent() {
        return this.disContent;
    }
    
    public void setDisContent(String disContent) {
        this.disContent = disContent;
    }

    /**
     * @return the disImage
     */
    public FormFile getDisImage() {
        return disImage;
    }

    /**
     * @param disImage the disImage to set
     */
    public void setDisImage(FormFile disImage) {
        this.disImage = disImage;
    }

    /**
     * @return the disImagePath
     */
    public String getDisImagePath() {
        return disImagePath;
    }

    /**
     * @param disImagePath the disImagePath to set
     */
    public void setDisImagePath(String disImagePath) {
        this.disImagePath = disImagePath;
    }

    /**
     * @return the labelId
     */
    public Integer getLabelId() {
        return labelId;
    }

    /**
     * @param labelId the labelId to set
     */
    public void setLabelId(Integer labelId) {
        this.labelId = labelId;
    }

    /**
     * @return the disPreventionContent
     */
    public String getDisPreventionContent() {
        return disPreventionContent;
    }

    /**
     * @param disPreventionContent the disPreventionContent to set
     */
    public void setDisPreventionContent(String disPreventionContent) {
        this.disPreventionContent = disPreventionContent;
    }

    /**
     * @return the disSpectrum
     */
    public String getDisSpectrum() {
        return disSpectrum;
    }

    /**
     * @param disSpectrum the disSpectrum to set
     */
    public void setDisSpectrum(String disSpectrum) {
        this.disSpectrum = disSpectrum;
    }




}


