package com.bpps.pojo;
// Generated 2012-6-10 23:02:51 by Hibernate Tools 3.2.1.GA

import org.apache.struts.upload.FormFile;




/**
 * Position generated by hbm2java
 */
public class Position extends org.apache.struts.action.ActionForm  implements java.io.Serializable {


     private Integer posId;
     private String posName;
     private String posDescribe;
     private String posImagePath;
     private FormFile posImage;
     private Integer labelId;

    public Position() {
    }

    public Position(String posName, String posDescribe) {
       this.posName = posName;
       this.posDescribe = posDescribe;
    }
   
    public Integer getPosId() {
        return this.posId;
    }
    
    public void setPosId(Integer posId) {
        this.posId = posId;
    }
    public String getPosName() {
        return this.posName;
    }
    
    public void setPosName(String posName) {
        if(posName==null)
            posName = "";
        this.posName = posName;
    }
    public String getPosDescribe() {
        return this.posDescribe;
    }
    
    public void setPosDescribe(String posDescribe) {
        if(posDescribe==null)
            posDescribe = "";
        this.posDescribe = posDescribe;
    }

    /**
     * @return the posImagePath
     */
    public String getPosImagePath() {
        return posImagePath;
    }

    /**
     * @param posImagePath the posImagePath to set
     */
    public void setPosImagePath(String posImagePath) {
        this.posImagePath = posImagePath;
    }

    /**
     * @return the posImage
     */
    public FormFile getPosImage() {
        return posImage;
    }

    /**
     * @param posImage the posImage to set
     */
    public void setPosImage(FormFile posImage) {
        this.posImage = posImage;
    }

    /**
     * @return the labelId
     */
    public Integer getLabelId() {
        return labelId;
    }

    /**
     * @param labelId the labelId to set
     */
    public void setLabelId(Integer labelId) {
        this.labelId = labelId;
    }




}


