package com.bpps.pojo;
// Generated 2012-6-10 23:02:51 by Hibernate Tools 3.2.1.GA

import org.apache.struts.upload.FormFile;




/**
 * PositionDisease generated by hbm2java
 */
public class PositionDisease  extends org.apache.struts.action.ActionForm  implements java.io.Serializable {


     private Integer posDisId;
     private int posId;
     private int disId;
     private int posDisFlag;
     private String posDisImagePath;
     private FormFile posDisImage;

    public PositionDisease() {
    }

    public PositionDisease(int posId, int disId, int posDisFlag) {
       this.posId = posId;
       this.disId = disId;
       this.posDisFlag = posDisFlag;
    }
   
    public Integer getPosDisId() {
        return this.posDisId;
    }
    
    public void setPosDisId(Integer posDisId) {
        this.posDisId = posDisId;
    }
    public int getPosId() {
        return this.posId;
    }
    
    public void setPosId(int posId) {
        this.posId = posId;
    }
    public int getDisId() {
        return this.disId;
    }
    
    public void setDisId(int disId) {
        this.disId = disId;
    }
    public int getPosDisFlag() {
        return this.posDisFlag;
    }
    
    public void setPosDisFlag(int posDisFlag) {
        this.posDisFlag = posDisFlag;
    }
    
    /**
     * @return the posDisImagePath
     */
    public String getPosDisImagePath() {
        return posDisImagePath;
    }

    /**
     * @param posDisImagePath the posDisImagePath to set
     */
    public void setPosDisImagePath(String posDisImagePath) {
        this.posDisImagePath = posDisImagePath;
    }

    /**
     * @return the posDisImage
     */
    public FormFile getPosDisImage() {
        return posDisImage;
    }

    /**
     * @param posDisImage the posDisImage to set
     */
    public void setPosDisImage(FormFile posDisImage) {
        this.posDisImage = posDisImage;
    }




}


