package com.bpps.pojo;
// Generated 2012-6-10 23:02:51 by Hibernate Tools 3.2.1.GA



/**
 * PositionSymptom generated by hbm2java
 */
public class PositionSymptom  implements java.io.Serializable {


     private Integer posSymId;
     private int posId;
     private int symId;

    public PositionSymptom() {
    }

    public PositionSymptom(int posId, int symId) {
       this.posId = posId;
       this.symId = symId;
    }
   
    public Integer getPosSymId() {
        return this.posSymId;
    }
    
    public void setPosSymId(Integer posSymId) {
        this.posSymId = posSymId;
    }
    public int getPosId() {
        return this.posId;
    }
    
    public void setPosId(int posId) {
        this.posId = posId;
    }
    public int getSymId() {
        return this.symId;
    }
    
    public void setSymId(int symId) {
        this.symId = symId;
    }




}


