package com.bpps.pojo;
// Generated 2012-6-10 23:02:51 by Hibernate Tools 3.2.1.GA



/**
 * Symptom generated by hbm2java
 */
public class Symptom extends org.apache.struts.action.ActionForm  implements java.io.Serializable {


     private Integer symId;
     private int posId;
     private String symName;
     private Integer symProperty;
     private Integer parentSymId;
     private Integer hasChild;
     private Integer labelId;

    public Symptom() {
    }

	
    public Symptom(int posId) {
        this.posId = posId;
    }
    public Symptom(int posId, String symName, Integer symProperty) {
       this.posId = posId;
       this.symName = symName;
       this.symProperty = symProperty;
    }
   
    public Integer getSymId() {
        return this.symId;
    }
    
    public void setSymId(Integer symId) {
        this.symId = symId;
    }
    public int getPosId() {
        return this.posId;
    }
    
    public void setPosId(int posId) {
        this.posId = posId;
    }
    public String getSymName() {
        return this.symName;
    }
    
    public void setSymName(String symName) {
        if(symName==null)
            symName = "";
        this.symName = symName;
    }
    public Integer getSymProperty() {
        return this.symProperty;
    }
    
    public void setSymProperty(Integer symProperty) {
        this.symProperty = symProperty;
    }

    /**
     * @return the parentSymId
     */
    public Integer getParentSymId() {
        return parentSymId;
    }

    /**
     * @param parentSymId the parentSymId to set
     */
    public void setParentSymId(Integer parentSymId) {
        this.parentSymId = parentSymId;
    }

    /**
     * @return the hasChild
     */
    public Integer getHasChild() {
        return hasChild;
    }

    /**
     * @param hasChild the hasChild to set
     */
    public void setHasChild(Integer hasChild) {
        this.hasChild = hasChild;
    }

    /**
     * @return the labelId
     */
    public Integer getLabelId() {
        return labelId;
    }

    /**
     * @param labelId the labelId to set
     */
    public void setLabelId(Integer labelId) {
        this.labelId = labelId;
    }




}


