package com.bpps.pojo;
// Generated 2012-6-10 23:02:51 by Hibernate Tools 3.2.1.GA



/**
 * SymptomDisease generated by hbm2java
 */
public class SymptomDisease extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private Integer posId;
     private int symId;
     private int disId;
     private String symDisDiscribe;
     private String posName;
     private String symName;
     private String disName;  
     private String disImagePath;

    public SymptomDisease() {
    }

	
    public SymptomDisease(int symId, int disId) {
        this.symId = symId;
        this.disId = disId;
    }
    public SymptomDisease(int symId, int disId, String symDisDiscribe) {
       this.symId = symId;
       this.disId = disId;
       this.symDisDiscribe = symDisDiscribe;
    }
   
    public int getSymId() {
        return this.symId;
    }
    
    public void setSymId(int symId) {
        this.symId = symId;
    }
    public int getDisId() {
        return this.disId;
    }
    
    public void setDisId(int disId) {
        this.disId = disId;
    }
    public String getSymDisDiscribe() {
        return this.symDisDiscribe;
    }
    
    public void setSymDisDiscribe(String symDisDiscribe) {
        this.symDisDiscribe = symDisDiscribe;
    }

    /**
     * @return the posId
     */
    public Integer getPosId() {
        return posId;
    }

    /**
     * @param posId the posId to set
     */
    public void setPosId(Integer posId) {
        this.posId = posId;
    }

    /**
     * @return the posName
     */
    public String getPosName() {
        return posName;
    }

    /**
     * @param posName the posName to set
     */
    public void setPosName(String posName) {
        this.posName = posName;
    }

    /**
     * @return the symName
     */
    public String getSymName() {
        return symName;
    }

    /**
     * @param symName the symName to set
     */
    public void setSymName(String symName) {
        this.symName = symName;
    }

    /**
     * @return the disName
     */
    public String getDisName() {
        return disName;
    }

    /**
     * @param disName the disName to set
     */
    public void setDisName(String disName) {
        this.disName = disName;
    }

    /**
     * @return the disImagePath
     */
    public String getDisImagePath() {
        return disImagePath;
    }

    /**
     * @param disImagePath the disImagePath to set
     */
    public void setDisImagePath(String disImagePath) {
        this.disImagePath = disImagePath;
    }




}


